### ISSUE TITLE
Parser Error: The identifier "cripter" isn't declared in the current scope.

### ISSUE THREAD

**Issue by Genie23** [Malkverbena/cripter#1]
Hello,

I want to know how I should install this module. Indeed, I copied the folder cripter in my module folder, then I try to do `var Cripte = cripter.new()` in the method _ready() of a scene, and it causes me an error Parser Error: The identifier "cripter" isn't declared in the current scope.

Cordially,

**Comment by Malkverbena** [comment]
Hello,
It's an error of script. There are a exemple how to use this. 
Remember, depending on the type of encryption you use you will need an RSA key or nothing gonna work.
Anyway,this branck are not ready to Godot 4 yet. On 3.2's branch should work fine.
As soon I get time I'll update a new version for 4.0's branch.

**Comment by Malkverbena** [comment]
Perhaps this article will help you.
https://rietta.com/blog/openssl-generating-rsa-key-from-command/

**Comment by Malkverbena** [comment]
Are you trying to use this module with Godot 4?

**Comment by Genie23** [comment]
No, I'm using Godot version 3.2.1

**Comment by Malkverbena** [comment]
I put an example project together with a pair of keys. This should be enough for anyone to run a basic project. Hope this helps you. Any doubt, just ask.
