### ISSUE TITLE
error scons Two environments

### ISSUE THREAD

**Issue by andolon** [Malkverbena/cripter#2]
I've got always same error when running scons.
Tested with godot.4.4 and godot3.5

`scons -j4 platform=x11 use_llvm=yes linker=lld tools=yes bits=64 target=release_debug;
scons: Reading SConscript files ...
Using linker program: lld

scons: *** Two environments with different actions were specified for the same target: /p1/godot-3.5-stable/thirdparty/mbedtls/library/error.x11.opt.tools.64.llvm.o
(action 1: clang -o error.x11.opt.tools.64.llvm.o -c -std=gnu11 -w -g2 -O2 -pipe -fpie -Wall -Wno-ordered-compare-function-pointers -w -DDEBUG_ENABLED -DNO_EDITOR_SPLASH -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DUDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DOPENGL_ENABLED -DGLES_ENABLED -D_FILE_OFFSET_BITS=64 -DPTRCALL_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL -DMBEDTLS_CONFIG_FILE=\"thirdparty/mbedtls/include/godot_module_mbedtls_config.h\" error.c)
(action 2: clang -o error.x11.opt.tools.64.llvm.o -c -std=gnu11 -w -g2 -O2 -pipe -fpie -Wall -Wno-ordered-compare-function-pointers -w -DDEBUG_ENABLED -DNO_EDITOR_SPLASH -DTOUCH_ENABLED -DALSA_ENABLED -DALSAMIDI_ENABLED -DPULSEAUDIO_ENABLED -D_REENTRANT -DJOYDEV_ENABLED -DUDEV_ENABLED -DX11_ENABLED -DUNIX_ENABLED -DOPENGL_ENABLED -DGLES_ENABLED -D_FILE_OFFSET_BITS=64 -DPTRCALL_ENABLED -DTOOLS_ENABLED -DMINIZIP_ENABLED -DZSTD_STATIC_LINKING_ONLY -DGLAD_ENABLED -DGLES_OVER_GL error.c)
File "/p1/godot-3.5-stable/methods.py", line 36, in add_source_files`

**Comment by Malkverbena** [comment]
This happens because the module compile the file "error.c" from mbedtls library again. 
For now it's ok. The module will compile and work fine.
Once a get some free time I'll fix this.

**Comment by Malkverbena** [comment]
@andolon It's fixed now.
